name: Deploy to local server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download code from GitHub
        uses: actions/checkout@v3

      - name: Clean up old Docker network
        run: |
          docker network rm todo_network 2>$null
          docker network prune -f 2>$null

      - name: Check Terraform
        run: C:\terraform\terraform.exe --version

      - name: Initialize Terraform
        run: |
          cd infra
          C:\terraform\terraform.exe init

      - name: Deploy infrastructure
        run: |
          cd infra
          C:\terraform\terraform.exe apply -auto-approve

      - name: Done
        run: echo "App is running at http://localhost:8001"