name: Deploy to local server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download code from GitHub
        uses: actions/checkout@v3

      - name: Check Terraform
        run: C:\terraform\terraform.exe --version

      - name: Initialize Terraform
        run: |
          cd infra
          $env:TF_PLUGIN_CACHE_DIR = ""
          $env:CHECKPOINT_DISABLE = "1"
          C:\terraform\terraform.exe init -plugin-dir="C:\terraform\plugins" -reconfigure
        shell: pwsh

      - name: Deploy infrastructure
        run: |
          cd infra
          $env:TF_PLUGIN_CACHE_DIR = ""
          $env:CHECKPOINT_DISABLE = "1"
          C:\terraform\terraform.exe apply -auto-approve
        shell: pwsh

      - name: Done
        run: echo "App is running at http://localhost:8001"